// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

void run_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
void ui_event_Dropdown4(lv_event_t * e);
extern lv_obj_t * ui_Dropdown4;
void ui_event_TextArea2(lv_event_t * e);
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_Keyboard1;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label13;
// CUSTOM VARIABLES
extern lv_obj_t * uic_weather_image;
extern lv_obj_t * uic_text_label_date;
extern lv_obj_t * uic_weather_image_temperature;
extern lv_obj_t * uic_text_label_temperature;
extern lv_obj_t * uic_text_label_humidity;
extern lv_obj_t * uic_weather_image_humidity;
extern lv_obj_t * uic_text_label_weather_description;
extern lv_obj_t * uic_text_label_time_location;

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
void ui_event_Screen4(lv_event_t * e);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Spinner2;
// CUSTOM VARIABLES

// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
void ui_event_Screen5(lv_event_t * e);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Calendar1;
void ui_event_Set_alarm(lv_event_t * e);
extern lv_obj_t * ui_Set_alarm;
extern lv_obj_t * ui_Label11;
void ui_event_Set_Wifi(lv_event_t * e);
extern lv_obj_t * ui_Set_Wifi;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label19;
// CUSTOM VARIABLES

// SCREEN: ui_Screen7
void ui_Screen7_screen_init(void);
extern lv_obj_t * ui_Screen7;
extern lv_obj_t * ui_Alarm;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label20;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Label22;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ui_Label18;

// SCREEN: ui_Screen9
void ui_Screen9_screen_init(void);
extern lv_obj_t * ui_Screen9;
extern lv_obj_t * ui_Checkbox1;
extern lv_obj_t * ui_Checkbox2;
extern lv_obj_t * ui_Checkbox4;
extern lv_obj_t * ui_Checkbox5;
extern lv_obj_t * ui_Checkbox6;
extern lv_obj_t * ui_Checkbox7;
extern lv_obj_t * ui_Checkbox8;
extern lv_obj_t * ui_Roller1;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Roller3;
// CUSTOM VARIABLES
extern lv_obj_t * uic_checkbox_monday;
extern lv_obj_t * uic_checkbox_tuesday;
extern lv_obj_t * uic_checkbox_sunday;
extern lv_obj_t * uic_checkbox_saturday;
extern lv_obj_t * uic_checkbox_friday;
extern lv_obj_t * uic_checkbox_thursday;
extern lv_obj_t * uic_checkbox_wednesday;

// SCREEN: ui_Screen10
void ui_Screen10_screen_init(void);
void ui_event_Screen10(lv_event_t * e);
extern lv_obj_t * ui_Screen10;
extern lv_obj_t * ui_Label10;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1895770859);    // assets/House-7.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
