// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _UI_COMP_PANEL1_H
#define _UI_COMP_PANEL1_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Panel1
#define UI_COMP_PANEL1_PANEL1 0
#define UI_COMP_PANEL1_LABEL18 1
#define UI_COMP_PANEL1_BUTTON6 2
#define UI_COMP_PANEL1_LABEL19 3
#define UI_COMP_PANEL1_SWITCH7 4
#define UI_COMP_PANEL1_LABEL16 5
#define _UI_COMP_PANEL1_NUM 6
lv_obj_t * ui_Panel1_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
