// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_comp_Container2_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Panel1_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Panel2_create_hook(lv_obj_t * comp)
{
}
