// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen7_screen_init(void)
{
    ui_Screen7 = lv_obj_create(NULL);

    ui_Alarm = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Alarm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alarm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Alarm, 3);
    lv_obj_set_y(ui_Alarm, -84);
    lv_obj_set_align(ui_Alarm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Alarm, "Alarm\n");
    lv_obj_set_style_text_font(ui_Alarm, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_button_create(ui_Screen7);
    lv_obj_set_width(ui_Button3, 41);
    lv_obj_set_height(ui_Button3, 42);
    lv_obj_set_x(ui_Button3, -125);
    lv_obj_set_y(ui_Button3, -88);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label12 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -126);
    lv_obj_set_y(ui_Label12, -88);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "<");
    lv_obj_set_style_text_decor(ui_Label12, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Screen7);
    lv_obj_set_width(ui_Panel2, 262);
    lv_obj_set_height(ui_Panel2, 131);
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, 22);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label20 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -72);
    lv_obj_set_y(ui_Label20, -25);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "00 : 00");
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_button_create(ui_Panel2);
    lv_obj_set_width(ui_Button2, 63);
    lv_obj_set_height(ui_Button2, 36);
    lv_obj_set_x(ui_Button2, 80);
    lv_obj_set_y(ui_Button2, -29);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label21 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 80);
    lv_obj_set_y(ui_Label21, -28);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "Edit");

    ui_Switch1 = lv_switch_create(ui_Panel2);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, 78);
    lv_obj_set_y(ui_Switch1, 38);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);


    ui_Label22 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, 2);
    lv_obj_set_y(ui_Label22, 10);
    lv_obj_set_align(ui_Label22, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label22, "");
    lv_obj_set_style_text_align(ui_Label22, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    uic_ui_Label18 = ui_Label21;

}
