// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"


// COMPONENT Panel1

lv_obj_t * ui_Panel1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Panel1;
    cui_Panel1 = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_Panel1, 262);
    lv_obj_set_height(cui_Panel1, 131);
    lv_obj_set_x(cui_Panel1, 0);
    lv_obj_set_y(cui_Panel1, 22);
    lv_obj_set_align(cui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Label18;
    cui_Label18 = lv_label_create(cui_Panel1);
    lv_obj_set_width(cui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label18, -72);
    lv_obj_set_y(cui_Label18, -25);
    lv_obj_set_align(cui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label18, "00 : 00");
    lv_obj_set_style_text_font(cui_Label18, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Button6;
    cui_Button6 = lv_button_create(cui_Panel1);
    lv_obj_set_width(cui_Button6, 63);
    lv_obj_set_height(cui_Button6, 36);
    lv_obj_set_x(cui_Button6, 80);
    lv_obj_set_y(cui_Button6, -29);
    lv_obj_set_align(cui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(cui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Label19;
    cui_Label19 = lv_label_create(cui_Panel1);
    lv_obj_set_width(cui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label19, 80);
    lv_obj_set_y(cui_Label19, -28);
    lv_obj_set_align(cui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label19, "Edit");

    lv_obj_t * cui_Switch7;
    cui_Switch7 = lv_switch_create(cui_Panel1);
    lv_obj_set_width(cui_Switch7, 50);
    lv_obj_set_height(cui_Switch7, 25);
    lv_obj_set_x(cui_Switch7, 78);
    lv_obj_set_y(cui_Switch7, 32);
    lv_obj_set_align(cui_Switch7, LV_ALIGN_CENTER);

    lv_obj_t * cui_Label16;
    cui_Label16 = lv_label_create(cui_Panel1);
    lv_obj_set_width(cui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label16, -194);
    lv_obj_set_y(cui_Label16, 14);
    lv_obj_set_align(cui_Label16, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(cui_Label16, "Text\n");
    lv_obj_set_style_text_align(cui_Label16, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_PANEL1_NUM);
    children[UI_COMP_PANEL1_PANEL1] = cui_Panel1;
    children[UI_COMP_PANEL1_LABEL18] = cui_Label18;
    children[UI_COMP_PANEL1_BUTTON6] = cui_Button6;
    children[UI_COMP_PANEL1_LABEL19] = cui_Label19;
    children[UI_COMP_PANEL1_SWITCH7] = cui_Switch7;
    children[UI_COMP_PANEL1_LABEL16] = cui_Label16;
    lv_obj_add_event_cb(cui_Panel1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Panel1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Panel1_create_hook(cui_Panel1);
    return cui_Panel1;
}

