// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void dropdown_event_handler(lv_event_t * e);
void button_event_handler(lv_event_t * e);
void weather_station_ui(lv_event_t * e);
void setup_time(lv_event_t * e);
void rescanWiFi(lv_event_t * e);
void save_alarm_settings(lv_event_t * e);
void stop_alarm_action(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
