// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen9_screen_init(void)
{
    ui_Screen9 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Checkbox1 = lv_checkbox_create(ui_Screen9);
    lv_checkbox_set_text(ui_Checkbox1, "Monday");
    lv_obj_set_width(ui_Checkbox1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox1, -92);
    lv_obj_set_y(ui_Checkbox1, -98);
    lv_obj_set_align(ui_Checkbox1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Checkbox2 = lv_checkbox_create(ui_Screen9);
    lv_checkbox_set_text(ui_Checkbox2, "Tuesday");
    lv_obj_set_width(ui_Checkbox2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox2, -91);
    lv_obj_set_y(ui_Checkbox2, -65);
    lv_obj_set_align(ui_Checkbox2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Checkbox4 = lv_checkbox_create(ui_Screen9);
    lv_checkbox_set_text(ui_Checkbox4, "Sunday");
    lv_obj_set_width(ui_Checkbox4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox4, -94);
    lv_obj_set_y(ui_Checkbox4, 100);
    lv_obj_set_align(ui_Checkbox4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Checkbox5 = lv_checkbox_create(ui_Screen9);
    lv_checkbox_set_text(ui_Checkbox5, "Saturday");
    lv_obj_set_width(ui_Checkbox5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox5, -89);
    lv_obj_set_y(ui_Checkbox5, 68);
    lv_obj_set_align(ui_Checkbox5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Checkbox6 = lv_checkbox_create(ui_Screen9);
    lv_checkbox_set_text(ui_Checkbox6, "Friday");
    lv_obj_set_width(ui_Checkbox6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox6, -99);
    lv_obj_set_y(ui_Checkbox6, 34);
    lv_obj_set_align(ui_Checkbox6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Checkbox7 = lv_checkbox_create(ui_Screen9);
    lv_checkbox_set_text(ui_Checkbox7, "Thursday");
    lv_obj_set_width(ui_Checkbox7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox7, -88);
    lv_obj_set_y(ui_Checkbox7, 1);
    lv_obj_set_align(ui_Checkbox7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Checkbox8 = lv_checkbox_create(ui_Screen9);
    lv_checkbox_set_text(ui_Checkbox8, "Wednesday");
    lv_obj_set_width(ui_Checkbox8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox8, -78);
    lv_obj_set_y(ui_Checkbox8, -32);
    lv_obj_set_align(ui_Checkbox8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Roller1 = lv_roller_create(ui_Screen9);
    lv_roller_set_options(ui_Roller1,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_Roller1, 52);
    lv_obj_set_height(ui_Roller1, 100);
    lv_obj_set_x(ui_Roller1, 30);
    lv_obj_set_y(ui_Roller1, -8);
    lv_obj_set_align(ui_Roller1, LV_ALIGN_CENTER);

    ui_Button5 = lv_button_create(ui_Screen9);
    lv_obj_set_width(ui_Button5, 82);
    lv_obj_set_height(ui_Button5, 39);
    lv_obj_set_x(ui_Button5, 101);
    lv_obj_set_y(ui_Button5, 81);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_Screen9);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 102);
    lv_obj_set_y(ui_Label17, 82);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "SAVE");

    ui_Roller3 = lv_roller_create(ui_Screen9);
    lv_roller_set_options(ui_Roller3,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_Roller3, 52);
    lv_obj_set_height(ui_Roller3, 100);
    lv_obj_set_x(ui_Roller3, 98);
    lv_obj_set_y(ui_Roller3, -7);
    lv_obj_set_align(ui_Roller3, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    uic_checkbox_monday = ui_Checkbox1;
    uic_checkbox_tuesday = ui_Checkbox2;
    uic_checkbox_sunday = ui_Checkbox4;
    uic_checkbox_saturday = ui_Checkbox5;
    uic_checkbox_friday = ui_Checkbox6;
    uic_checkbox_thursday = ui_Checkbox7;
    uic_checkbox_wednesday = ui_Checkbox8;

}
